api_version = "2025-07"

[[extensions]]
name = "melon-x-checkout-ui"
handle = "melon-x-checkout-ui"
type = "ui_extension"
uid = "1bdfef1e-e15d-a8b9-3b2c-0338e467164887e3e8ac"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.thank-you.block.render"

[extensions.capabilities]
api_access = true
network_access = true

[[extensions.metafields]]
namespace = "$app"

key = "requestedFreeGift"

[extensions.settings]
[[extensions.settings.fields]]
key = "shopify_app_url"
type = "single_line_text_field"
name = "Shopify App URL"
description = "Your Shopify app tunnel or production URL (no trailing slash)"

